apiVersion: apps/v1
kind: Deployment
metadata:
  name: StudentManagement
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: StudentManagement
  template:
    metadata:
      labels:
        app: StudentManagement
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 3; done']
      containers:
        - name: StudentManagement
          image: samargouader001/StudentManagement:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  selector:
    app: StudentManagement
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 32639
  type: NodePort
