apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmanagement   # lowercase
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmanagement
  template:
    metadata:
      labels:
        app: studentmanagement
    spec:
      containers:
        - name: studentmanagement   # lowercase
          image: samargouader001/studentmanagement:latest
          ports:
            - containerPort: 8080
